/* This file was auto-generated by KreMLin! */

#include "PKCS11_Test.h"

FStar_Pervasives_either__bool_PKCS11_Exception_exception_t
checkAttributes(attribute_t *attr, mechanism m)
{
  return
    (
      (FStar_Pervasives_either__bool_PKCS11_Exception_exception_t){
        .tag = FStar_Pervasives_Inl,
        { .case_Inl = { .v = true } }
      }
    );
}

uint32_t
_CK_C_GenerateKey(
  uint32_t hSession,
  _CK_MECHANISM pMechanism,
  _CK_ATTRIBUTE *pTemplate,
  uint32_t usCount,
  uint32_t phKey
)
{
  (void)PKCS11_Objects_getTheReference(phKey);
  return
    castExpectionToRV((
        (FStar_Pervasives_either__bool_PKCS11_Exception_exception_t){
          .tag = FStar_Pervasives_Inl,
          { .case_Inl = { .v = true } }
        }
      ));
}

