/* This file was auto-generated by KreMLin! */

#include "PKCS11_Exception.h"

bool uu___is_CKR_GENERAL_ERROR(exp_ckr_general projectee)
{
  if (projectee == CKR_GENERAL_ERROR)
    return true;
  else
    return false;
}

bool uu___is_CKR_HOST_MEMORY(exp_ckr_general projectee)
{
  if (projectee == CKR_HOST_MEMORY)
    return true;
  else
    return false;
}

bool uu___is_CKR_FUNCTION_FAILED(exp_ckr_general projectee)
{
  if (projectee == CKR_FUNCTION_FAILED)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_HANDLE_INVALID(exp_ckr_session projectee)
{
  if (projectee == CKR_SESSION_HANDLE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_DEVICE_REMOVED_Session(exp_ckr_session projectee)
{
  if (projectee == CKR_DEVICE_REMOVED_Session)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_CLOSED(exp_ckr_session projectee)
{
  if (projectee == CKR_SESSION_CLOSED)
    return true;
  else
    return false;
}

bool uu___is_CKR_DEVICE_MEMORY(exp_ckr_token projectee)
{
  if (projectee == CKR_DEVICE_MEMORY)
    return true;
  else
    return false;
}

bool uu___is_CKR_DEVICE_ERROR(exp_ckr_token projectee)
{
  if (projectee == CKR_DEVICE_ERROR)
    return true;
  else
    return false;
}

bool uu___is_CKR_TOKEN_NOT_PRESENT(exp_ckr_token projectee)
{
  if (projectee == CKR_TOKEN_NOT_PRESENT)
    return true;
  else
    return false;
}

bool uu___is_CKR_DEVICE_REMOVED_Token(exp_ckr_token projectee)
{
  if (projectee == CKR_DEVICE_REMOVED_Token)
    return true;
  else
    return false;
}

bool uu___is_CKR_CANCEL(exp_ckr_callback projectee)
{
  return true;
}

bool uu___is_CKR_MUTEX_BAD(exp_ckr_mutex projectee)
{
  if (projectee == CKR_MUTEX_BAD)
    return true;
  else
    return false;
}

bool uu___is_CKR_MUTEX_NOT_LOCKED(exp_ckr_mutex projectee)
{
  if (projectee == CKR_MUTEX_NOT_LOCKED)
    return true;
  else
    return false;
}

bool uu___is_CKR_ACTION_PROHIBITED(exp_ckr_other projectee)
{
  if (projectee == CKR_ACTION_PROHIBITED)
    return true;
  else
    return false;
}

bool uu___is_CKR_ARGUMENTS_BAD(exp_ckr_other projectee)
{
  if (projectee == CKR_ARGUMENTS_BAD)
    return true;
  else
    return false;
}

bool uu___is_CKR_ATTRIBUTE_READ_ONLY(exp_ckr_other projectee)
{
  if (projectee == CKR_ATTRIBUTE_READ_ONLY)
    return true;
  else
    return false;
}

bool uu___is_CKR_ATTRIBUTE_SENSITIVE(exp_ckr_other projectee)
{
  if (projectee == CKR_ATTRIBUTE_SENSITIVE)
    return true;
  else
    return false;
}

bool uu___is_CKR_ATTRIBUTE_TYPE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_ATTRIBUTE_TYPE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_ATTRIBUTE_VALUE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_ATTRIBUTE_VALUE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_BUFFER_TOO_SMALL(exp_ckr_other projectee)
{
  if (projectee == CKR_BUFFER_TOO_SMALL)
    return true;
  else
    return false;
}

bool uu___is_CKR_CANT_LOCK(exp_ckr_other projectee)
{
  if (projectee == CKR_CANT_LOCK)
    return true;
  else
    return false;
}

bool uu___is_CKR_CRYPTOKI_ALREADY_INITIALIZED(exp_ckr_other projectee)
{
  if (projectee == CKR_CRYPTOKI_ALREADY_INITIALIZED)
    return true;
  else
    return false;
}

bool uu___is_CKR_CRYPTOKI_NOT_INITIALIZED(exp_ckr_other projectee)
{
  if (projectee == CKR_CRYPTOKI_NOT_INITIALIZED)
    return true;
  else
    return false;
}

bool uu___is_CKR_CURVE_NOT_SUPPORTED(exp_ckr_other projectee)
{
  if (projectee == CKR_CURVE_NOT_SUPPORTED)
    return true;
  else
    return false;
}

bool uu___is_CKR_DATA_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_DATA_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_DATA_LEN_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_DATA_LEN_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_DOMAIN_PARAMS_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_DOMAIN_PARAMS_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_ENCRYPTED_DATA_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_ENCRYPTED_DATA_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_ENCRYPTED_DATA_LEN_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_ENCRYPTED_DATA_LEN_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_EXCEEDED_MAX_ITERATIONS(exp_ckr_other projectee)
{
  if (projectee == CKR_EXCEEDED_MAX_ITERATIONS)
    return true;
  else
    return false;
}

bool uu___is_CKR_FIPS_SELF_TEST_FAILED(exp_ckr_other projectee)
{
  if (projectee == CKR_FIPS_SELF_TEST_FAILED)
    return true;
  else
    return false;
}

bool uu___is_CKR_FUNCTION_CANCELED(exp_ckr_other projectee)
{
  if (projectee == CKR_FUNCTION_CANCELED)
    return true;
  else
    return false;
}

bool uu___is_CKR_FUNCTION_NOT_PARALLEL(exp_ckr_other projectee)
{
  if (projectee == CKR_FUNCTION_NOT_PARALLEL)
    return true;
  else
    return false;
}

bool uu___is_CKR_FUNCTION_NOT_SUPPORTED(exp_ckr_other projectee)
{
  if (projectee == CKR_FUNCTION_NOT_SUPPORTED)
    return true;
  else
    return false;
}

bool uu___is_CKR_FUNCTION_REJECTED(exp_ckr_other projectee)
{
  if (projectee == CKR_FUNCTION_REJECTED)
    return true;
  else
    return false;
}

bool uu___is_CKR_INFORMATION_SENSITIVE(exp_ckr_other projectee)
{
  if (projectee == CKR_INFORMATION_SENSITIVE)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_CHANGED(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_CHANGED)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_FUNCTION_NOT_PERMITTED(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_FUNCTION_NOT_PERMITTED)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_HANDLE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_HANDLE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_INDIGESTIBLE(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_INDIGESTIBLE)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_NEEDED(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_NEEDED)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_NOT_NEEDED(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_NOT_NEEDED)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_NOT_WRAPPABLE(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_NOT_WRAPPABLE)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_SIZE_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_SIZE_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_TYPE_INCONSISTENT(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_TYPE_INCONSISTENT)
    return true;
  else
    return false;
}

bool uu___is_CKR_KEY_UNEXTRACTABLE(exp_ckr_other projectee)
{
  if (projectee == CKR_KEY_UNEXTRACTABLE)
    return true;
  else
    return false;
}

bool uu___is_CKR_LIBRARY_LOAD_FAILED(exp_ckr_other projectee)
{
  if (projectee == CKR_LIBRARY_LOAD_FAILED)
    return true;
  else
    return false;
}

bool uu___is_CKR_MECHANISM_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_MECHANISM_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_MECHANISM_PARAM_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_MECHANISM_PARAM_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_NEED_TO_CREATE_THREADS(exp_ckr_other projectee)
{
  if (projectee == CKR_NEED_TO_CREATE_THREADS)
    return true;
  else
    return false;
}

bool uu___is_CKR_NO_EVENT(exp_ckr_other projectee)
{
  if (projectee == CKR_NO_EVENT)
    return true;
  else
    return false;
}

bool uu___is_CKR_OBJECT_HANDLE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_OBJECT_HANDLE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_OPERATION_ACTIVE(exp_ckr_other projectee)
{
  if (projectee == CKR_OPERATION_ACTIVE)
    return true;
  else
    return false;
}

bool uu___is_CKR_OPERATION_NOT_INITIALIZED(exp_ckr_other projectee)
{
  if (projectee == CKR_OPERATION_NOT_INITIALIZED)
    return true;
  else
    return false;
}

bool uu___is_CKR_PIN_EXPIRED(exp_ckr_other projectee)
{
  if (projectee == CKR_PIN_EXPIRED)
    return true;
  else
    return false;
}

bool uu___is_CKR_PIN_INCORRECT(exp_ckr_other projectee)
{
  if (projectee == CKR_PIN_INCORRECT)
    return true;
  else
    return false;
}

bool uu___is_CKR_PIN_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_PIN_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_PIN_LEN_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_PIN_LEN_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_PIN_LOCKED(exp_ckr_other projectee)
{
  if (projectee == CKR_PIN_LOCKED)
    return true;
  else
    return false;
}

bool uu___is_CKR_PIN_TOO_WEAK(exp_ckr_other projectee)
{
  if (projectee == CKR_PIN_TOO_WEAK)
    return true;
  else
    return false;
}

bool uu___is_CKR_PUBLIC_KEY_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_PUBLIC_KEY_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_RANDOM_NO_RNG(exp_ckr_other projectee)
{
  if (projectee == CKR_RANDOM_NO_RNG)
    return true;
  else
    return false;
}

bool uu___is_CKR_RANDOM_SEED_NOT_SUPPORTED(exp_ckr_other projectee)
{
  if (projectee == CKR_RANDOM_SEED_NOT_SUPPORTED)
    return true;
  else
    return false;
}

bool uu___is_CKR_SAVED_STATE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_SAVED_STATE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_COUNT(exp_ckr_other projectee)
{
  if (projectee == CKR_SESSION_COUNT)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_EXISTS(exp_ckr_other projectee)
{
  if (projectee == CKR_SESSION_EXISTS)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_PARALLEL_NOT_SUPPORTED(exp_ckr_other projectee)
{
  if (projectee == CKR_SESSION_PARALLEL_NOT_SUPPORTED)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_READ_ONLY(exp_ckr_other projectee)
{
  if (projectee == CKR_SESSION_READ_ONLY)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_READ_ONLY_EXISTS(exp_ckr_other projectee)
{
  if (projectee == CKR_SESSION_READ_ONLY_EXISTS)
    return true;
  else
    return false;
}

bool uu___is_CKR_SESSION_READ_WRITE_SO_EXISTS(exp_ckr_other projectee)
{
  if (projectee == CKR_SESSION_READ_WRITE_SO_EXISTS)
    return true;
  else
    return false;
}

bool uu___is_CKR_SIGNATURE_LEN_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_SIGNATURE_LEN_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_SIGNATURE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_SIGNATURE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_SLOT_ID_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_SLOT_ID_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_STATE_UNSAVEABLE(exp_ckr_other projectee)
{
  if (projectee == CKR_STATE_UNSAVEABLE)
    return true;
  else
    return false;
}

bool uu___is_CKR_TEMPLATE_INCOMPLETE(exp_ckr_other projectee)
{
  if (projectee == CKR_TEMPLATE_INCOMPLETE)
    return true;
  else
    return false;
}

bool uu___is_CKR_TEMPLATE_INCONSISTENT(exp_ckr_other projectee)
{
  if (projectee == CKR_TEMPLATE_INCONSISTENT)
    return true;
  else
    return false;
}

bool uu___is_CKR_TOKEN_NOT_RECOGNIZED(exp_ckr_other projectee)
{
  if (projectee == CKR_TOKEN_NOT_RECOGNIZED)
    return true;
  else
    return false;
}

bool uu___is_CKR_TOKEN_WRITE_PROTECTED(exp_ckr_other projectee)
{
  if (projectee == CKR_TOKEN_WRITE_PROTECTED)
    return true;
  else
    return false;
}

bool uu___is_CKR_UNWRAPPING_KEY_HANDLE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_UNWRAPPING_KEY_HANDLE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_UNWRAPPING_KEY_SIZE_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_UNWRAPPING_KEY_SIZE_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT(exp_ckr_other projectee)
{
  if (projectee == CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT)
    return true;
  else
    return false;
}

bool uu___is_CKR_USER_ALREADY_LOGGED_IN(exp_ckr_other projectee)
{
  if (projectee == CKR_USER_ALREADY_LOGGED_IN)
    return true;
  else
    return false;
}

bool uu___is_CKR_USER_ANOTHER_ALREADY_LOGGED_IN(exp_ckr_other projectee)
{
  if (projectee == CKR_USER_ANOTHER_ALREADY_LOGGED_IN)
    return true;
  else
    return false;
}

bool uu___is_CKR_USER_NOT_LOGGED_IN(exp_ckr_other projectee)
{
  if (projectee == CKR_USER_NOT_LOGGED_IN)
    return true;
  else
    return false;
}

bool uu___is_CKR_USER_PIN_NOT_INITIALIZED(exp_ckr_other projectee)
{
  if (projectee == CKR_USER_PIN_NOT_INITIALIZED)
    return true;
  else
    return false;
}

bool uu___is_CKR_USER_TOO_MANY_TYPES(exp_ckr_other projectee)
{
  if (projectee == CKR_USER_TOO_MANY_TYPES)
    return true;
  else
    return false;
}

bool uu___is_CKR_USER_TYPE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_USER_TYPE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_WRAPPED_KEY_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_WRAPPED_KEY_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_WRAPPED_KEY_LEN_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_WRAPPED_KEY_LEN_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_WRAPPING_KEY_HANDLE_INVALID(exp_ckr_other projectee)
{
  if (projectee == CKR_WRAPPING_KEY_HANDLE_INVALID)
    return true;
  else
    return false;
}

bool uu___is_CKR_WRAPPING_KEY_SIZE_RANGE(exp_ckr_other projectee)
{
  if (projectee == CKR_WRAPPING_KEY_SIZE_RANGE)
    return true;
  else
    return false;
}

bool uu___is_CKR_WRAPPING_KEY_TYPE_INCONSISTENT(exp_ckr_other projectee)
{
  if (projectee == CKR_WRAPPING_KEY_TYPE_INCONSISTENT)
    return true;
  else
    return false;
}

bool uu___is_G(exception_t projectee)
{
  if (projectee.tag == G)
    return true;
  else
    return false;
}

exp_ckr_general __proj__G__item__exp(exception_t projectee)
{
  if (projectee.tag == G)
  {
    exp_ckr_general exp = projectee.case_G.exp;
    return exp;
  }
  else
  {
    printf("KreMLin abort at %s:%d\n%s\n", __FILE__, __LINE__, "no else in F*");
    exit(255U);
  }
}

bool uu___is_S(exception_t projectee)
{
  if (projectee.tag == S)
    return true;
  else
    return false;
}

exp_ckr_session __proj__S__item__exp(exception_t projectee)
{
  if (projectee.tag == S)
  {
    exp_ckr_session exp = projectee.case_S.exp;
    return exp;
  }
  else
  {
    printf("KreMLin abort at %s:%d\n%s\n", __FILE__, __LINE__, "no else in F*");
    exit(255U);
  }
}

bool uu___is_T(exception_t projectee)
{
  if (projectee.tag == T)
    return true;
  else
    return false;
}

exp_ckr_token __proj__T__item__exp(exception_t projectee)
{
  if (projectee.tag == T)
  {
    exp_ckr_token exp = projectee.case_T.exp;
    return exp;
  }
  else
  {
    printf("KreMLin abort at %s:%d\n%s\n", __FILE__, __LINE__, "no else in F*");
    exit(255U);
  }
}

bool uu___is_C(exception_t projectee)
{
  if (projectee.tag == C)
    return true;
  else
    return false;
}

exp_ckr_callback __proj__C__item__exp(exception_t projectee)
{
  if (projectee.tag == C)
  {
    exp_ckr_callback exp = projectee.case_C.exp;
    return exp;
  }
  else
  {
    printf("KreMLin abort at %s:%d\n%s\n", __FILE__, __LINE__, "no else in F*");
    exit(255U);
  }
}

bool uu___is_M(exception_t projectee)
{
  if (projectee.tag == M)
    return true;
  else
    return false;
}

exp_ckr_mutex __proj__M__item__exp(exception_t projectee)
{
  if (projectee.tag == M)
  {
    exp_ckr_mutex exp = projectee.case_M.exp;
    return exp;
  }
  else
  {
    printf("KreMLin abort at %s:%d\n%s\n", __FILE__, __LINE__, "no else in F*");
    exit(255U);
  }
}

bool uu___is_O(exception_t projectee)
{
  if (projectee.tag == O)
    return true;
  else
    return false;
}

exp_ckr_other __proj__O__item__exp(exception_t projectee)
{
  if (projectee.tag == O)
  {
    exp_ckr_other exp = projectee.case_O.exp;
    return exp;
  }
  else
  {
    printf("KreMLin abort at %s:%d\n%s\n", __FILE__, __LINE__, "no else in F*");
    exit(255U);
  }
}

bool uu___is_TestExc(exception_t projectee)
{
  if (projectee.tag == TestExc)
    return true;
  else
    return false;
}

