/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __PKCS11_Test_H
#define __PKCS11_Test_H


#include "PKCS11_DateTime.h"
#include "PKCS11_TypeDeclaration.h"
#include "PKCS11_Mechanism.h"
#include "PKCS11_Attribute.h"
#include "PKCS11_Cast.h"
#include "PKCS11_Exception.h"
#include "PKCS11_Objects.h"
#include "PKCS11_Parse.h"
#include "PKCS11_Pointer.h"


typedef uint32_t _CK_RV0;

typedef bool _CK_BBOOL;

typedef uint32_t *_CK_OBJECT_CLASS;

typedef uint32_t int1;

typedef struct 
{
  FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t_tags tag;
  union {
    struct  { bool v; } case_Inl;
    struct  { exception_t v; } case_Inr;
  }
  ;
}
FStar_Pervasives_either__bool_PKCS11_Exception_exception_t;

FStar_Pervasives_either__bool_PKCS11_Exception_exception_t
checkAttributes(attribute_t *attr, mechanism m);

uint32_t
_CK_C_GenerateKey(
  uint32_t hSession,
  _CK_MECHANISM pMechanism,
  _CK_ATTRIBUTE *pTemplate,
  uint32_t usCount,
  uint32_t phKey
);
#endif
