/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __PKCS11_Pointer_H
#define __PKCS11_Pointer_H


#include "PKCS11_DateTime.h"
#include "PKCS11_TypeDeclaration.h"
#include "PKCS11_Mechanism.h"
#include "PKCS11_Attribute.h"
#include "PKCS11_Cast.h"
#include "PKCS11_Exception.h"
#include "PKCS11_Objects.h"
#include "PKCS11_Parse.h"


typedef void *_CK_VOID_PTR;

extern bool *castToBool0();
#endif
