/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __PKCS11_Parse_H
#define __PKCS11_Parse_H


#include "PKCS11_DateTime.h"
#include "PKCS11_TypeDeclaration.h"
#include "PKCS11_Mechanism.h"
#include "PKCS11_Attribute.h"
#include "PKCS11_Cast.h"
#include "PKCS11_Exception.h"
#include "PKCS11_Objects.h"


bool attributesIsReadOnly__PKCS11_TypeDeclaration__CK_ATTRIBUTE_TYPE(uint32_t uu___48_478);

typedef struct 
{
  FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t_tags tag;
  union {
    struct  { attribute_t v; } case_Inl;
    struct  { exception_t v; } case_Inr;
  }
  ;
}
FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t_PKCS11_Exception_exception_t;

FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t_PKCS11_Exception_exception_t
parseAttribute(_CK_ATTRIBUTE attr_r);

typedef struct 
{
  FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t_tags tag;
  union {
    struct  { attribute_t *v; } case_Inl;
    struct  { exception_t v; } case_Inr;
  }
  ;
}
FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t__PKCS11_Exception_exception_t;

extern FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t__PKCS11_Exception_exception_t
_parseAttributes(_CK_ATTRIBUTE *x0, attribute_t *x1);

extern FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t__PKCS11_Exception_exception_t
parseAttributes(_CK_ATTRIBUTE *x0);

extern void rng_algorithm(uint8_t *x0, uint32_t x1);

extern void rng_algorithm2(uint8_t *x0, uint32_t x1);

typedef struct 
{
  FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t_tags tag;
  union {
    struct  { mechanism v; } case_Inl;
    struct  { exception_t v; } case_Inr;
  }
  ;
}
FStar_Pervasives_either__PKCS11_TypeDeclaration_mechanism_PKCS11_Exception_exception_t;
#endif
