/* This file was auto-generated by KreMLin! */

#include "PKCS11_Parse.h"

bool attributesIsReadOnly__PKCS11_TypeDeclaration__CK_ATTRIBUTE_TYPE(uint32_t uu___48_478)
{
  return false;
}

FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t_PKCS11_Exception_exception_t
parseAttribute(_CK_ATTRIBUTE attr_r)
{
  uint32_t typ = attributeRawGetTypeID(attr_r);
  _CK_VOID_PTR data = attributeRawGetData(attr_r);
  uint32_t length1 = attributeRawGetLength(attr_r);
  if (FStar_UInt32_v(typ) == (krml_checked_int_t)0)
  {
    uint32_t *pointer = castToUlong(data);
    return
      (
        (FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t_PKCS11_Exception_exception_t){
          .tag = FStar_Pervasives_Inl,
          {
            .case_Inl = {
              .v = {
                .tag = CKA_CLASS,
                .val = {
                  .case_CKA_CLASS = {
                    .typeId = typ,
                    .pValue = pointer,
                    .ulValueLength = changeSizeOfBuffer(length1),
                    .isReadOnly = attributesIsReadOnly__PKCS11_TypeDeclaration__CK_ATTRIBUTE_TYPE(typ)
                  }
                }
              }
            }
          }
        }
      );
  }
  else
    return
      (
        (FStar_Pervasives_either__PKCS11_TypeDeclaration_attribute_t_PKCS11_Exception_exception_t){
          .tag = FStar_Pervasives_Inr,
          { .case_Inr = { .v = { .tag = TestExc } } }
        }
      );
}

