/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __PKCS11_Cast_H
#define __PKCS11_Cast_H


#include "PKCS11_DateTime.h"
#include "PKCS11_TypeDeclaration.h"
#include "PKCS11_Mechanism.h"
#include "PKCS11_Attribute.h"


extern bool *castToBool(_CK_VOID_PTR x0);

extern uint32_t *castToUlong(_CK_VOID_PTR x0);

extern uint32_t changeSizeOfBuffer(uint32_t x0);
#endif
