/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __PKCS11_Objects_H
#define __PKCS11_Objects_H


#include "PKCS11_DateTime.h"
#include "PKCS11_TypeDeclaration.h"
#include "PKCS11_Mechanism.h"
#include "PKCS11_Attribute.h"
#include "PKCS11_Cast.h"
#include "PKCS11_Exception.h"


typedef enum { FStar_Pervasives_Inl, FStar_Pervasives_Inr }
FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t_tags;

typedef struct 
{
  FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t_tags tag;
  union {
    struct  { uint8_t *v; } case_Inl;
    struct  { exception_t v; } case_Inr;
  }
  ;
}
FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t;

extern FStar_Pervasives_either__uint8_t__PKCS11_Exception_exception_t
PKCS11_Objects_getTheReference(uint32_t x0);
#endif
