/* This file was auto-generated by KreMLin! */

#include "PKCS11_DateTime.h"

bool PKCS11_DateTime_uu___is_MakeDate(PKCS11_DateTime_date projectee)
{
  return true;
}

uint8_t PKCS11_DateTime___proj__MakeDate__item__day(PKCS11_DateTime_date projectee)
{
  PKCS11_DateTime_date scrut = projectee;
  uint8_t day = scrut.day;
  return day;
}

uint8_t PKCS11_DateTime___proj__MakeDate__item__month(PKCS11_DateTime_date projectee)
{
  PKCS11_DateTime_date scrut = projectee;
  uint8_t month = scrut.month;
  return month;
}

uint8_t PKCS11_DateTime___proj__MakeDate__item__year(PKCS11_DateTime_date projectee)
{
  PKCS11_DateTime_date scrut = projectee;
  uint8_t year = scrut.year;
  return year;
}

